"""Rename type to image_type in images table

Revision ID: d0d51596a332
Revises: 10697125fb86
Create Date: 2025-03-06 01:16:34.238431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0d51596a332'
down_revision = '10697125fb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_type', sa.String(length=10), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('image_type')

    # ### end Alembic commands ###
